config/routes.rb
Rails.application.routes.draw do

  
  root 'chatroom#index'

  get 'login',:to => "sessions#new"
  post 'login',:to => "sessions#create"
  delete 'logout',:to => "sessions#destroy"

  get 'signup',:to => "users#new"
  post 'signup',:to => "users#create"


  post 'message',:to => "messages#create"

  mount ActionCable.server ,at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body,presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    validates :username,uniqueness:{case_sensitive: false},presence: true,length:{minimum:3, maximum: 12}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user , :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            # flash[:notice]="You must be logged in to perform this action"
            redirect_to login_path
        end
    end

    
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @messages=Message.custom_display
        @message=Message.new
    end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user


    def create

       message=current_user.messages.build(message_params)

        if message.save
            ActionCable.server.broadcast "chatroom_channel",
                                        :message => render_message(message)
        else
            flash[:error]="Some error occured ...could not submit message!"
            redirect_to root_path
        end

    end

    private

    def message_params

        params.require(:message).permit(:body,:user_id)
    end

    def render_message(message)
        render(partial: 'message' , locals:{message: message})
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect ,only: [:new,:create]
    
    def new
            
    end

    def create
        
        user=User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[:success]="Logged In Successfully"
            redirect_to root_path

        else

            flash[:now]="Error!Check Username/Password"
            render 'new'
        end

    end

    def destroy

       
        session[:user_id]=nil
        flash[:success] = "Logged Out!"
        redirect_to login_path
    end

    private 

    def logged_in_redirect
        if logged_in?
            redirect_to root_path 
        end
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user=User.new
    end

    def create
        @user=User.new(user_params)
        
        p_mismatch=false
        if(params[:session][:password]!=params[:session][:cpassword])
            p_mismatch=true 
        end

        
        if(!p_mismatch && @user.save)
            
            flash[:success]="User has been created"
            session[:user_id]=@user.id
            redirect_to root_path
        else
        
            if(p_mismatch && !@user.errors.any?)
                @user.errors.add(:base,"Password did not match..Try again!")
            end

            render 'new'
        end
    end

    private 

    def user_params
        params.require(:session).permit(:username,:password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular green chat icon"></i>
  Friends
</h4>

<div class="ui two column grid">

    <div class="twelve wide column">
         <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-render">
                    <!-- The below line automatically looks for messages/message partial 
                        and iterates through the @messages objects and renders the html
                      -->
                    <%= render @messages  %>
                </div>
            </div>
            <div class="extra content">

                <%= form_for(@message,html:{class: "ui reply form",role: "form"},url: message_path  , remote: true ) do |f| %>
                    <div class="ui fluid icon input">
                        <%= f.text_field "body", placeholder: "Enter a message",id: "message-input" %>
                        <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    
    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
    

</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type,message| %>
    <div class="ui message transition <%=  message_type=="success" ? :green : :red %>">
        <i class="close icon"></i>
        <div class="header">
            <%= message %>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
    <div class="ui container">

        <% if logged_in? %>
            <%= link_to 'Chatroom', root_path,:class=>"item" %>
        
            <a class="item">
            Messages
            </a>
        <% end %>

        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if logged_in? %>
                        <%= link_to 'Log Out', logout_path,:method => "delete" ,:class=>"item" %>
                    <% else %>
                        <%= link_to 'Log In', login_path,:class=>"item" %>
                    <% end %>
                </div>
            </div>
            <% unless logged_in? %>
                <div class="item">
                    <%= link_to 'Log In', login_path,:class=>"ui primary button" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>
   
    
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>

  <script>

    
      
  </script>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular black user icon"></i>
  Signup
</h4>




 <%= form_for("session", html: {class: "ui form signup-form", role: "form"},url: signup_path ) do |f| %>
  <div class="field">
    <%= f.label "username","Username" %>
    <%= f.text_field "username", placeholder: "Username" %>
  </div>
  <div class="field">
    <%= f.label "password","Password" %>
    <%= f.password_field "password", placeholder: "Password" %>
  </div>
  <div class="field">
    <%= f.label "cpassword","Confirm Password" %>
    <%= f.password_field "cpassword", placeholder: "Confirm Password" %>
  </div>
  
   <%= f.button "Sign Up", class: "ui blue submit button" %>
<% end %>

<% if @user.errors.any? %>
<div class="ui message transition red custom-error">
    <i class="close icon"></i>
    <% @user.errors.full_messages.each do |message| %>
    <div class="header">
        <%= message %>
    </div>
    <% end %>

</div>
<% end %>